describe('Launch QALab', ()=>{
    it('QALab testing', ()=>{
        cy.visit('http://qalab.pl.tivixlabs.com/',{failOnStatusCode: false})
        cy.url().should('include','tivixlabs')
        cy.title().should('eq','Car rent')
        cy.contains('Please fill pickup and drop off dates')
        cy.get('#model').type('Toyota Aygo-11-20')
        //cy.get("select").select(1).invoke("val").should("eq", "France")
        cy.get('#pickup').type('2022-11-20')
        cy.get('#dropoff').type('2022-11-21')
        cy.get("button[type='submit']").click()
        cy.go('back')
        cy.wait(200)
        cy.go('forward')
        cy.title().should('eq','Car rent')
        cy.get("a[href='/details/4']").click()
        //cy.get("a[href='/details/4']").click()
        cy.get('.btn.btn-primary').click()
        cy.get('#name').type('ghghhhh')
        cy.get('#last_name').type('ghghhhh')
        cy.get('#card_number').type('434343434343')
        cy.get('#email').type('ghg@hhhh')
        cy.get("button[type='submit']").click()

    })
})
